# Generated by Django 4.2.8 on 2023-12-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_productcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='email',
            field=models.EmailField(max_length=60),
        ),
    ]
