# Generated by Django 4.2.8 on 2023-12-27 16:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_productcomment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='feedback',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
    ]
