# Generated by Django 4.2.8 on 2023-12-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_productcomment_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='checkbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='feedback',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
